/**
 * German formatting, hand-rolled.
 *
 * Intl / toLocaleString / localeCompare are FORBIDDEN in this artifact: their output
 * depends on the ICU version bundled with Node, so the generated bytes would not be
 * stable across machines. Everything here is pure arithmetic and fixed tables.
 *
 * Date.now() and argument-less `new Date()` are likewise forbidden. All dates derive
 * from BASE_DATE via explicit offsets.
 */

const MS_PER_DAY = 86_400_000;

const WEEKDAYS_EN = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const;
const MONTHS_EN = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
] as const;

function at<T>(items: readonly T[], index: number): T {
  const value = items[index];
  if (value === undefined) throw new Error(`index ${index} out of range`);
  return value;
}

/** Parses "YYYY-MM-DD" into a UTC epoch. Explicit parts only — no locale parsing. */
export function parseIsoDate(iso: string): number {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  if (!match) throw new Error(`not an ISO date: ${iso}`);
  const [, y, m, d] = match;
  if (!y || !m || !d) throw new Error(`not an ISO date: ${iso}`);
  return Date.UTC(Number(y), Number(m) - 1, Number(d));
}

export function addDays(epochMs: number, days: number): number {
  return epochMs + days * MS_PER_DAY;
}

export function addMinutes(epochMs: number, minutes: number): number {
  return epochMs + minutes * 60_000;
}

/** "10.07.2026" */
export function deDate(epochMs: number): string {
  const d = new Date(epochMs);
  return `${pad2(d.getUTCDate())}.${pad2(d.getUTCMonth() + 1)}.${d.getUTCFullYear()}`;
}

/** "10.07.2026 09:14" */
export function deDateTime(epochMs: number): string {
  const d = new Date(epochMs);
  return `${deDate(epochMs)} ${pad2(d.getUTCHours())}:${pad2(d.getUTCMinutes())}`;
}

/** "2026-07-10T09:14:00Z" — the manifest's machine-readable form. */
export function isoDateTime(epochMs: number): string {
  return new Date(epochMs).toISOString().replace(/\.\d{3}Z$/, "Z");
}

export function isoDate(epochMs: number): string {
  const d = new Date(epochMs);
  return `${d.getUTCFullYear()}-${pad2(d.getUTCMonth() + 1)}-${pad2(d.getUTCDate())}`;
}

/**
 * EU summer time: last Sunday in March 01:00 UTC until last Sunday in October 01:00 UTC.
 * Needed so the .eml Date: headers carry a plausible +0200 / +0100 offset.
 */
export function berlinOffsetMinutes(epochMs: number): number {
  const year = new Date(epochMs).getUTCFullYear();
  const start = lastSundayUtc(year, 2, 1);
  const end = lastSundayUtc(year, 9, 1);
  return epochMs >= start && epochMs < end ? 120 : 60;
}

function lastSundayUtc(year: number, monthIndex: number, hourUtc: number): number {
  const lastDay = new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate();
  const weekday = new Date(Date.UTC(year, monthIndex, lastDay)).getUTCDay();
  return Date.UTC(year, monthIndex, lastDay - weekday, hourUtc);
}

/** RFC 5322: "Thu, 09 Jul 2026 11:14:00 +0200" */
export function rfc5322Date(epochMs: number): string {
  const offset = berlinOffsetMinutes(epochMs);
  const local = new Date(epochMs + offset * 60_000);
  const sign = offset >= 0 ? "+" : "-";
  const abs = Math.abs(offset);
  return (
    `${at(WEEKDAYS_EN, local.getUTCDay())}, ${pad2(local.getUTCDate())} ` +
    `${at(MONTHS_EN, local.getUTCMonth())} ${local.getUTCFullYear()} ` +
    `${pad2(local.getUTCHours())}:${pad2(local.getUTCMinutes())}:${pad2(local.getUTCSeconds())} ` +
    `${sign}${pad2(Math.floor(abs / 60))}${pad2(abs % 60)}`
  );
}

const WEEKDAYS_DE = [
  "Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag",
] as const;
const MONTHS_DE = [
  "Januar", "Februar", "März", "April", "Mai", "Juni",
  "Juli", "August", "September", "Oktober", "November", "Dezember",
] as const;

/**
 * "Donnerstag, 14. März 2024 16:42" — the form a German Outlook writes into the
 * "Gesendet:" line of a quoted message. Local Berlin time, hand-formatted (no Intl).
 */
export function deLongDateTime(epochMs: number): string {
  const local = new Date(epochMs + berlinOffsetMinutes(epochMs) * 60_000);
  return (
    `${at(WEEKDAYS_DE, local.getUTCDay())}, ${local.getUTCDate()}. ` +
    `${at(MONTHS_DE, local.getUTCMonth())} ${local.getUTCFullYear()} ` +
    `${pad2(local.getUTCHours())}:${pad2(local.getUTCMinutes())}`
  );
}

/** "1.234,56" — thousands dot, decimal comma. Hand-rolled; no Intl. */
export function deNumber(value: number, decimals = 2): string {
  const negative = value < 0;
  const fixed = Math.abs(value).toFixed(decimals);
  const dot = fixed.indexOf(".");
  const intPart = dot === -1 ? fixed : fixed.slice(0, dot);
  const fracPart = dot === -1 ? "" : fixed.slice(dot + 1);
  let grouped = "";
  for (let i = 0; i < intPart.length; i++) {
    const remaining = intPart.length - i;
    grouped += at([...intPart], i);
    if (remaining > 1 && remaining % 3 === 1) grouped += ".";
  }
  const body = fracPart ? `${grouped},${fracPart}` : grouped;
  return negative ? `-${body}` : body;
}

/** "1.234,56 EUR" */
export function deEuro(value: number, decimals = 2): string {
  return `${deNumber(value, decimals)} EUR`;
}

function pad2(n: number): string {
  return n < 10 ? `0${n}` : String(n);
}

/**
 * Codepoint sort. Array.prototype.sort() is already codepoint-based for strings, but
 * calling this makes the intent explicit and guards against someone reaching for
 * localeCompare, which would be ICU-version dependent.
 */
export function sortByCodepoint(items: readonly string[]): string[] {
  return [...items].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}
